# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WHwG-XHFgOlwuWcNF9ugHgVW_bhm5uv-
"""



set={[1,2,3,4,5,'human'],[1,2,3,4,5,'human']}

b=[1,2,3,4,5,6]

b.pop()

b

#list
a = [1, 2, 3, 4, 5, 'human']
b = [[1, 2, 3, 4, 5, 'human'], [2, 3, 4, 5, 'human'], [3, 4, 5, 'human']]

#tuple
a = (1, 2, 3, 4, 5, 'human')

#set
a= {1, 2, 3, 4, 5, 'human'}

#dictionary
a = {'list': [1, 2, 3, 4, 5, 'human'],
     'tuple': (1, 2, 3, 4, 5, 'human'),
     'set': {1, 2, 3, 4, 5, 'human'}}

if 2 in b :
  print('true')
else:
    print('false')

7 in b