# -*- coding: utf-8 -*-
"""Copy of CW_RollNoJ019_040720

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mJ6Zrgn-z-Cv3ppzx_ZVJSDWydi9UvSi
"""

a
b

import

a=5
a='five'

print(5)

a=4
c=6

del b

if b>0 : 
    print('a')

def printer():
    a=5
    b=6
    print(a+b)
def sum(a,b):
    return a+b

printer()

a=c

a

if a==c:

int('1B1212',12)

str(float(int('111',3)))

def sum() :
    a= 'sjkd jasbaksd bkasdj 
    asjdba ksdb sajdb '

help(traceback)

a_=4 # for using reserve keywords
__a__=5
a=6
_a=9 # variable is intended for internal use (private variables)
__a=91 #

def make_a(a,class_):
    pass

#public variable vs private

class human:
    """ Members of a class """
    # attribute - variables - compulsory
    # method/behaviour- function - compulsory

class Student:
    a =6
    def __init__(self,name):
        #Instatiates the object of a class ~ constructor
        #print(name) 
        self.__name = name 
        #self.__a=6
  
    def displayName(self): 
        print(self.__name)
        #print(self.__a) 
  
#Class vs Object
s1 = Student("Santhosh") 
s1.displayName() 
  
# Raises an error 
print(s1.__name)

class student1(Student):
    #     def __init__(self,name):
    #     print(self.a)
    #     print(self.__name)

s2=student1('Santosh1')

import pandas as pd

lis=['a','b','c']
a=pd.DataFrame(columns=lis)

a=pd.read_csv('https://people.sc.fsu.edu/~jburkardt/data/csv/addresses.csv')

b=pd.read

# Create a custom class DataRead to read csv file using pandas
# Create a custom function RowSelect within the class to select any 2 rows of the the the dataframe
# Create a sub class of DataRead1 as  DataRead2  that has function for correlation plots (using any lib for correlation plot)
# Within DataRead2 also create a function to override the custom function of DataRead1 RowSelect to select 3 rows

s1._Student__a

dir(s1)

float(int('111',3))

a='a'

type(a)

sum(a,c)

b

# list 
a = [1,2,3,4,5,'human']
b=[[1,2,3,4,5,'human'],[1,2,3,4,5],[3,4,5,'human']]

#tuple
a = (1,2,3,4,5,'human')

#set
a = {1,2,3,4,5,'human'}


# dictionary
a= {'list':[1,2,3,4,5,'human'],
     'tuple':(1,2,3,4,5,'human'),
    'set': {1,2,3,4,5,'human'}}

b={[1,2,3,4,5,'human'],[1,2,3,4,5,'human']}

b={0,7,1,2,2,4,5,6,-1}
print(b)

b.pop()
print(b)

b.pop

a*n
a+a+a+a+

b

b.pop()

b.pop()

b.pop()

if 2 in b : 
    print('true')
else:
    print('false')

b={1,2,3,4,5}
7 in b

#Q1

print ("Hello World!")
