# -*- coding: utf-8 -*-
"""HW_J003_110720.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/FlintyTub49/Sem_V-Artificial-Intelligence/blob/master/Homework/HW_J003_110720.ipynb
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

class DataRead():
  def __init__(self,filename):
    self.data = pd.read_csv(filename)

  def display_rows(self,x,y):
    print(self.data.iloc[[x, y]])

class DataRead2(DataRead):
  #def __init__(self, filename):
    #DataRead.__init__(DataRead, filename)

  def plot_correlation(self):
    temp_data = self.data
    correlation = temp_data.corr()
    sns.heatmap(correlation)
    plt.show()

  def display_rows(self,x,y,z):
    print(self.data.iloc[[x, y, z]])

"""###Creating a custom class to read the data into a Pandas DataFrame"""

filename = 'datasets_19_420_Iris.csv'
s1 = DataRead(filename)
print(s1.data.head())

"""###Creating a custom function RowSelect within the class to select any 2 rows of the choice of the user to be displayed from the dataframe"""

x = int(input('Enter row number to be displayed: '))
y = int(input('Enter row number to be displayed: '))
s1.display_rows(x-1,y-1)

"""### Creating a DataRead1 as DataRead2 that has a function for correlation plots"""

s2 = DataRead2(filename)
s2.plot_correlation()

"""### Within DataRead2, creating a function to override the custom function of DataRead1 RowSelect to select 3 rows"""

x = int(input('Enter row number to be displayed: '))
y = int(input('Enter row number to be displayed: '))
z = int(input('Enter row number to be displayed: '))
s2.display_rows(x-1,y-1,z-1)